apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rockynewapp
  name: rockynewapp
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: rockynewapp
  type: NodePort
status:
  loadBalancer: {}
