pipeline {
    agent any
      environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
                HOME = "${env.WORKSPACE}"
      }
    stages {
        stage('Checkout') {
            steps {
                echo "Hello Rocky World ${BUILD_NUMBER}"
                git branch: 'main', url: 'https://github.com/rocky19devops/myrepo.git'
            }
        }

        stage('Build') {
            steps {
                echo 'Building the Docker Image..............'
                sh "cd rockyapp && docker build -t rocky19devops/rockyapp:${BUILD_NUMBER} ."
                }
        }

        stage('Push Code') {
          environment {
            DOCKER_IMAGE = "rocky19devops/rockyapp:${BUILD_NUMBER}"
            REGISTRY_CREDENTIALS = credentials('rockydockerhub')
          }
            steps {
              script {
                def dockerImage = docker.image("${DOCKER_IMAGE}")
                docker.withRegistry('https://index.docker.io/v1/', "rockydockerhub") {
                dockerImage.push()
                }
            }
            }
        }

        stage('Run') {
            steps {
                echo 'Run the docker application............'
                sh "docker run -d -p 9090:9090 --name rockyapp${BUILD_NUMBER} rocky19devops/rockyapp:${BUILD_NUMBER}"
            }
        }

        stage('Validate') {
            steps {
                echo 'Validate the application............'
                sh "curl -v http://`hostname -i`:9090"
            }
        }
    }
}
