pipeline {
    agent any
      environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
                HOME = "${env.WORKSPACE}"
      }
    stages {
        stage('Checkout') {
            steps {
                echo "Hello Rocky World ${BUILD_NUMBER}"
                git branch: 'main', url: 'https://github.com/rocky19devops/myrepo.git'
            }
        }

        stage('Build') {
            steps {
                echo 'Building the Docker Image..............'
                sh "cd rockyapp && docker build -t rocky19devops/rockyapp:${BUILD_NUMBER} ."
                }
        }

        stage('Push Code') {
          environment {
            DOCKER_IMAGE = "rocky19devops/rockyapp:${BUILD_NUMBER}"
            REGISTRY_CREDENTIALS = credentials('rockydockerhub')
          }
            steps {
              script {
                def dockerImage = docker.image("${DOCKER_IMAGE}")
                docker.withRegistry('https://index.docker.io/v1/', "rockydockerhub") {
                dockerImage.push()
                }
            }
            }
        }

        stage('Deploy K8s') {
          environment {
            GIT_REPO_NAME = "myrepo"
            GIT_USER_NAME = "rocky19devops"
          }
            steps {
                git branch: 'main', url: "https://github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git"
                withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                    sh '''
                    echo Deploy application in k8s environment ...............
                    git config user.email "rajesh19.soft@gmail.com"
                    git config user.name "Rajesh Kumar Ramesh"
                    BUILD_NUMBER=${BUILD_NUMBER}
                    ls -ltrh
                    git status
                    cd kube
                    pwd
                    sed -i -r "s/rockyapp(.+)/rockyapp:${BUILD_NUMBER}/g" Deployment.yaml
                    git status
                    git add Deployment.yml -v
                    git status
                    git commit -m "Update deployment image to version ${BUILD_NUMBER}" -v
                    git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
                '''
               }
            }
           
        }

        stage('Validate') {
            steps {
                echo 'Validate the application............'
                sh "curl -v http://`hostname -i`:9090"
            }
        }
    }

}
